# Generated by Django 3.0.2 on 2020-01-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='name',
        ),
    ]
