# Generated by Django 3.0.2 on 2020-01-24 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0003_writer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='name',
        ),
    ]
