# Generated by Django 3.0.2 on 2020-01-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0004_remove_writer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='photo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
