# Generated by Django 3.0.2 on 2020-01-25 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0005_writer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='photo',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wapp.Writer')),
            ],
        ),
    ]
