# Generated by Django 3.0.2 on 2020-01-25 13:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import wapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('wapp', '0006_auto_20200125_0844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.AlterField(
            model_name='writer',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=wapp.models.contact_default),
        ),
    ]
